schema: workflow/2022.04
name: Scrape
triggers:
- id: ti_wMTEdJp
steps:
- namespace: get_request
  runtime: nodejs18.x
  uses: http-get-request@1.1.1
  props:
    httpRequest:
      auth:
        type: none
        username: ''
        password: ''
        token: ''
      body:
        contentType: none
        fields: []
        mode: fields
        type: raw
      headers: []
      method: GET
      params:
      - name: ''
        value: ''
        disabled: true
      url: https://www.bidrustbelt.com/Browse?FullTextQuery=dumbbell
      tab: Auth
- namespace: node
  runtime: nodejs18.x
  uses: "./node/entry.js"
  props:
    htmlContent: "{{steps.get_request.$return_value}}"
- namespace: add_update_record
  runtime: nodejs18.x
  uses: data_stores-add-update-record@0.0.9
  props:
    dataStore:
      storeId: ds_aQudl3
    key:
      __lv:
        label: seen_listings
        value: seen_listings
    value: "[{{steps.node.$return_value[0].listingId}}, ...]"
- namespace: send_message_public_channel
  runtime: nodejs18.x
  uses: slack-send-message-public-channel@0.2.17
  props:
    slack:
      authProvisionId: apn_b6hOkMO
    conversation:
      __lv:
        label: pierces-playground
        value: C04AG7G17EG
    text: "{{steps.node.$return_value[0].imageUrl}}"

